name: Build xash3d for linux

on:
  workflow_dispatch:

jobs:
  android:
   name: Setup
   runs-on: ubuntu-latest
   steps:
   - name: Checkout sources
     uses: actions/checkout@v3
     with:
          fetch-depth: 0
          submodules: recursive
   - uses: actions/checkout@v3
   - uses: actions/setup-java@v3
     with:
      distribution: 'zulu' # See 'Supported distributions' for available options
      java-version: '8'
   - run: | 
           sudo apt-get update
           sudo apt install build-essential cmake make gcc g++ gcc-multilib g++-multilib libfontconfig1-dev libfreetype6-dev libsdl2-dev
           git clone --recursive https://github.com/ValveSoftware/halflife hlsdk/
           mkdir build && cd build
           cmake .. -DHL_SDK_DIR=../hlsdk
           make -j8
           mkdir installed
           make install installed/
   - name: Upload artifacts
     uses: actions/upload-artifact@v3
     with:
          name: compiled
          path: build/installed
